FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && \
    apt-get -y install python3 python3-venv libpython3.11-dev redis firefox-esr graphviz imagemagick librsvg2-bin fonts-dejavu shellcheck
